### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Nekro64** [Nekro64/Charades#1]
- [ ] Button "addPoint" changing color. When team wins- green, when lose-red, when is a tie- orange

- [ ] Script for "changeTeamNameButton" button

- [ ] Insert timer script

- [ ]  Optimization CSS code

- [ ] Script for "column-2" and "column-1"

- [ ] Insert svg
